### ISSUE TITLE
急急急，ie下无法首先导出任何文件

### ISSUE THREAD

**Issue by cddsgtc** [huanz/tableExport#15]

**Comment by huanz** [comment]
@cddsgtc 请看你的浏览器是否在支持版本内？

**Comment by cddsgtc** [comment]
@huanz 
我还以为你放弃这个东西了呢，已经解决了。
但是想问先，tableexport('table','test','type')中第一个参数只能使用id吗，而且第二个参数是做什么用的？

**Comment by huanz** [comment]
@cddsgtc 目前第一个只能是 id，第二个是文件名称，一直想着升级下来着然而一直也没抽出时间来

**Comment by cddsgtc** [comment]
@huanz 
加油啊，我昨天试了npm库导出table数据的一些包——tableExport,jquery-export-plugin,table-expoter..
发现还是你这个最好用。
