### ISSUE TITLE
pdf导出

### ISSUE THREAD

**Issue by chris-paul** [huanz/tableExport#2]
您好  为什么我导出pdf的时候数据显示不全，经常有一块黑色呢

**Comment by huanz** [comment]
麻烦发一下你的html

On 周二, 5月 31, 2016 at 10:02, 廉恒凯 <notifications@github.com> wrote:
您好 为什么我导出pdf的时候数据显示不全，经常有一块黑色呢

**Comment by chris-paul** [comment]
当我把您的代码下载下来的时候，运行demo文件夹里面的index.html,
![image](https://cloud.githubusercontent.com/assets/18257755/15661143/96273c12-2717-11e6-9ea0-150be4e44969.png)

**Comment by huanz** [comment]
@chris-paul 那你是什么浏览器呢？以及版本？

**Comment by chris-paul** [comment]
您好，谢谢您的答复 没想到回的这么快 ，我的浏览器是谷歌浏览器的最新版啊，我在火狐里面试了pdf整个页面都是黑色，在您的电脑上可以测试成功吗

**Comment by huanz** [comment]
@chris-paul 在我这里没有问题。我不同版本测测吧

**Comment by chris-paul** [comment]
谢谢 因为在项目中用到了您的这个导出项目，测试的时候其他的格式都没有问题，就是pdf有问题

**Comment by chris-paul** [comment]
您好 您测试的时候发现了这个问题吗

**Comment by huanz** [comment]
@chris-paul 已经修复了，你可以试下

**Comment by chris-paul** [comment]
您好  我只要替换了tableExport.js就可以了吧

**Comment by chris-paul** [comment]
您多加几条数据  貌似还是不行

**Comment by huanz** [comment]
@chris-paul 我再多测测

**Comment by chris-paul** [comment]
万分感谢

**Comment by huanz** [comment]
@chris-paul fixed

**Comment by chris-paul** [comment]
好了  万分谢谢
