### ISSUE TITLE
有合并的单元格能处理吗？

### ISSUE THREAD

**Issue by DevYan** [huanz/tableExport#5]

**Comment by huanz** [comment]
@DevYan 可以处理，但是导出的可能没有合并单元格了

**Comment by DevYan** [comment]
@huanz 比较期望能够导出的excel和页面上展示的一样，我看到[这个](https://github.com/tarunbatta/ExcelExportJs)是可以的

**Comment by huanz** [comment]
@DevYan 因为我对表格进行处理了，你可以直接取`offilce = $('table')[0].outerHTML`的内容[#9](https://github.com/huanz/tableExport/blob/master/src/office.js#L8)
